### ISSUE TITLE
[Bug]: Authorize button in stream deck does not work

### ISSUE THREAD

**Issue by tjwrona** [XeroxDev/YTMD-StreamDeck#101]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

I just updated to the latest version and I can't seem to get it to authenticate with the YTMusic desktop app. I updated both the app as well as the plugin to the latest versions today.

I made sure all the settings here were correct. But when I click "Authorize" from within the stream deck nothing happens and the button continues to not work. 

![image](https://github.com/XeroxDev/YTMD-StreamDeck/assets/44857895/6f618210-74be-432d-94d9-e943b3594ddc)
![image](https://github.com/XeroxDev/YTMD-StreamDeck/assets/44857895/970feaf0-3da3-4510-98f5-19ff55812e01)

### Expected Behavior

It is expected that the authorize button would trigger the YTMusic Desktop app to authenticate and connect to the plugin.

### Steps To Reproduce

1. Update everything to the latest (YTMusic Desktop, Stream Deck, And this plugn)
2. Enable the browser communication and companion authorization in the YTMusicDesktop settings
3. Add a play/pause button and try to authenticate

### OS

Windows

### OS Version

11

### Plugin Version

v2.0.0

### YTMDesktop Version

v2.0.0

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment]
Yeah. I made a mistake while building the plugin (no issues with the source code, just the artifact / plugin file).

I've uploaded the correct file now and everything should work.

The download is (still) here https://github.com/XeroxDev/YTMD-StreamDeck/releases/tag/v2.0.0

Sorry!

/close
