### ISSUE TITLE
Wont Connect After Update[Bug]: <title>

### ISSUE THREAD

**Issue by juniorthomason** [XeroxDev/YTMD-StreamDeck#106]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

When clicking the Authorize button it will not connect to YouTube Music. Also with version 2.1.0 there isn't an option to input the password anymore. It try's to connect but it times out after a little while.

### Expected Behavior

I expect it to connect to YouTube Music.

### Steps To Reproduce

Click the Authorize button.

### OS

Mac

### OS Version

MacOS Ventura

### Plugin Version

13.2.1

### YTMDesktop Version

v2.1.0

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment]
Hey and thank you for your ticket!

1. You've switched up the "Plugin Version" and the "YTMDesktop Version".
2. v2.x of the Plugin only supports v2.x of YTMDesktop now. v1.x isn't supported anymore. Please install the [latest YTMDestkop Version](https://github.com/ytmdesktop/ytmdesktop/releases)
3. In v2 of YTMDesktop there isn't a password anymore. The authorization process was completely changed.

For the new authorization/connection process of V2, please see the updated [How to use it?](https://github.com/XeroxDev/YTMD-StreamDeck?tab=readme-ov-file#6-how-to-use-it) section.

After upgrading your YTMDesktop Applicaton and following the "How to", everything should work as expected and you can have an improved (YT)Music (Desktop) Feeling. I'll /close this for now. Feel free to reopen it, if you've still trouble with connecting!
