### ISSUE TITLE
I can not access your app

### ISSUE THREAD

**Issue by fasgamingttv** [XeroxDev/YTMD-StreamDeck#114]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

I tried to download your app each time coming up with page not found. Has it been taken down??

**Comment by Freddyb888** [comment]
SAME HERE

**Comment by lemanutitou** [comment]
Bonjour, pareil pour moi.

**Comment by XeroxDev** [comment]
This is a /duplicate of #111

Please see the mentioned ticket for more information.
