### ISSUE TITLE
[Bug]: Streamdeck to YTMD cant get server info

### ISSUE THREAD

**Issue by EnderVaedorn** [XeroxDev/YTMD-StreamDeck#115]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

Put shortly, The Desktop app itself currently has no ui element present to allow the user to obtain the required Host name and port for the Companion Server

### Expected Behavior

A way to access the information, as was previously available.

### Steps To Reproduce

Go to Integrations in Setting
Toggle on the Companion Server
No information given and no further interactables to get information
![image](https://github.com/XeroxDev/YTMD-StreamDeck/assets/162649705/de40717f-41d0-494e-ac2f-dbac01e3828e)
![image](https://github.com/XeroxDev/YTMD-StreamDeck/assets/162649705/73070e11-66d6-4e52-b137-115d1d512dc4)
![image](https://github.com/XeroxDev/YTMD-StreamDeck/assets/162649705/852c4996-a5f6-481a-8db0-9ac7f79e929b)

### OS

Windows

### OS Version

11

### Plugin Version

v2.1.0

### YTMDesktop Version

v2.0.5

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment]
Hey! That's currently a known bug. It should normally has a default value but somehow it fails to populate it.

This will be fixed in the next version. In the meantime, please see and follow https://help.xeroxdev.de/en/stream-deck/ytmd/home#h-5-how-to-use-it

**Comment by Kigster85** [comment]
just add in for host Localhost and port 9863 then try to auth again

**Comment by runningwolfie** [comment]
I'm still having an issue with this. I followed the steps on the link XeroxDev provided and I can successfully get an authorization from YTMD. However, it seems my info isn't saved by the plugin. Pressing play/pause makes the button get stuck on play, and nothing happens on YTMD. Also, it seems that the host and port aren't saved; when I click away and go back to the play/pause button settings (on Stream Deck), the information is gone. So it seems like the authorization happens but then the information is lost by the plugin.

**Comment by XeroxDev** [comment]
The information are still there and saved. They just don't get displayed. Please update the plugin to the latest version (via releases) to fix the display bug.
