### ISSUE TITLE
[Bug]: Previously liked song doesn't show up as liked song

### ISSUE THREAD

**Issue by Lua-kr** [XeroxDev/YTMD-StreamDeck#116]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

When I switched to liked song, Like button blinks to liked (full heart) and turn back to normal heart icon

### Expected Behavior

It should show up as liked song with full heart icon on like button

### Steps To Reproduce

1. Play already liked song
2. Check the like button on the Stream deck
3. It should have full heart icon on the like button

### OS

Windows

### OS Version

10

### Plugin Version

v2.1.0

### YTMDesktop Version

v2.0.5

### How did you download the software?

GitHub

**Comment by scotte** [comment]
I can confirm seeing this behavior. Additionally, after liking a song the stream deck button resets after 30 seconds or so to un-liked state.
