### ISSUE TITLE
[QUESTION]: Play and pause no longer working

### ISSUE THREAD

**Issue by Hayden9444** [XeroxDev/YTMD-StreamDeck#124]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

I had set up the plugin and it randomly broke. Now it no longer gives me an option to input the remote password and doesn't come including the port. How do i fix this?

**Comment by Hayden9444** [comment]
also now has an authorize button, when i click it i get a authentication failed error

**Comment by XeroxDev** [comment]
It seems like you're still on YTMDesktop Version 1. This version is outdated and not supported anymore like mentioned here
![image](https://github.com/XeroxDev/YTMD-StreamDeck/assets/10864620/c071f264-8245-4958-a7f2-0ca04bf23be9)

Please update your YTMDesktop to Version 2. If you need help authorizing it with the latest version, please follow the "How to use it" section in the [README](https://github.com/XeroxDev/YTMD-StreamDeck?tab=readme-ov-file#6-how-to-use-it) or [Helpdesk](https://help.xeroxdev.de/en/stream-deck/ytmd/home#h-5-how-to-use-it).

After that, everything should work.

**Comment by Hayden9444** [comment]
Updated to the newest version, enabled the companion server and the authorization, same error when i try to authorize. Do i need the port and IP? if so how do i find that

**Comment by XeroxDev** [comment]
The default host/ip is: 127.0.0.1
The default port is: 9863

In the latest version of the plugin this will auto-populate again. But it seems Elgato didn't publish the latest version yet. You can either insert them manually and wait until Elgato publishes the plugin to the marketplace or update the plugin now using the `streamDeckPlugin` file on the [release page](https://github.com/XeroxDev/YTMD-StreamDeck/releases)

**Comment by Hayden9444** [comment]
Hi,
I updated to version 2 of the youtube music app, but don't know where to
find my host or port, (both are blank on the stream deck). Now that i
cant get the ip from the remote control and the port isnt automatically
added where do i find them.
Thanks

**Comment by XeroxDev** [comment]
Our messages probably overlapped, let me quote myself, just to keep the order of messages correct.

> The default host/ip is: 127.0.0.1 The default port is: 9863
> 
> In the latest version of the plugin this will auto-populate again. But it seems Elgato didn't publish the latest version yet. You can either insert them manually and wait until Elgato publishes the plugin to the marketplace or update the plugin now using the `streamDeckPlugin` file on the [release page](https://github.com/XeroxDev/YTMD-StreamDeck/releases)
