### ISSUE TITLE
[QUESTION]: <its not letting me connect >

### ISSUE THREAD

**Issue by Narnar-Codes** [XeroxDev/YTMD-StreamDeck#126]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

when ever I click authorize I get this error 
![Screenshot 2024-06-20 132403](https://github.com/XeroxDev/YTMD-StreamDeck/assets/61482604/bebed078-8a5a-4071-a184-d7a0d988c13c)

**Comment by XeroxDev** [comment]
This bug is because your host and port settings are empty. You can either fill them out manually or update the plugin to the latest version using the plugin file in the [release tab](https://github.com/XeroxDev/YTMD-StreamDeck/releases/)

/close
