### ISSUE TITLE
I dont understand the steps

### ISSUE THREAD

**Issue by zacistoasty** [XeroxDev/YTMD-StreamDeck#127]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

I got to step 7 and and it still doesnt work. should i at this point have the host and port in there? if so how do i find it?

**Comment by XeroxDev** [comment]
The default host/ip is: 127.0.0.1
The default port is: 9863

In the latest version of the plugin this will auto-populate again. But it seems Elgato didn't publish the latest version yet (was published a while ago here on github...). You can either insert them manually and wait until Elgato publishes the plugin to the marketplace or update the plugin now using the `streamDeckPlugin` file on the [release page](https://github.com/XeroxDev/YTMD-StreamDeck/releases)

/close

**Comment by zacistoasty** [comment]
omg tysm
