### ISSUE TITLE
[FEATURE] Now playing icon/thumbnail

### ISSUE THREAD

**Issue by flaree** [XeroxDev/YTMD-StreamDeck#13]
**Is your feature request related to a problem? Please describe.**
No, it's not related to a problem.

**Describe the solution you'd like**
The ability to add a key that shows the song thumbnail if one is playing, optionally song name/artist name depending on size.

**Describe alternatives you've considered**
N/

**Additional context**
n/a

**Comment by INFlNlTY** [comment]
Additional request for this feature - the ability to span the now playing to 2-3 boxes (difficult to read 1 tile).
If there is a way to do this on my side, apologies for being a newby.

This is by far my favorite feature, also helps me share music to others. Thanks for making this plugin, it's lovely.
