### ISSUE TITLE
[QUESTION]: Use track image as button icon

### ISSUE THREAD

**Issue by YaddyVirus** [XeroxDev/YTMD-StreamDeck#131]
### Consent

- [x] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

I'd like to use the track image that shows up in the track info icon as icon for buttons. For example, I was playing around with the plugin and found that pressing the track info button also plays/pauses tracks. If possible, it'd be great if I could use this image as an icon for the play/pause, repeat, and any other buttons. 

I've looked around in the code and didn't find any obvious ways to do this. If you can point me in the right direction, I can do it myself, just need to know how the whole thing works.

**Comment by XeroxDev** [comment]
Hey!

First: I won't officially implement this. 

But sure! I will help you / pinpoint you to the right direction, so you can implement it for you privately.

Looking at this line of code https://github.com/XeroxDev/YTMD-StreamDeck/blob/master/src%2Factions%2Fsong-info.action.ts#L125 you can see how I fetch the image and set it as the icon. This should work for any other action as well.

Feel free to close this issue anytime, if you have everything you need.
