### ISSUE TITLE
[Bug]: <title>Authentication Failed - Failed to fetch error

### ISSUE THREAD

**Issue by ChroNick37** [XeroxDev/YTMD-StreamDeck#140]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

Authentication Failed - Failed to fetch error when trying to connect youtube music app

### Expected Behavior

pause/play YT music from stream deck

### Steps To Reproduce

n/a

### OS

Windows

### OS Version

11

### Plugin Version

6.7.3 (21005)

### YTMDesktop Version

v2.0.5

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment]
Due to missing responses, I think this fixed the issue. So I'm gonna /close this now. Have fun controlling YTMDesktop with your device!

**Comment by spkpal** [comment]
Hey

I am having a problem connecting my youtube desktop app to my stream deck

it keeps on saying this to me, Authentication failed
