### ISSUE TITLE
[BUG] mute does not work 

### ISSUE THREAD

**Issue by the-jomper** [XeroxDev/YTMD-StreamDeck#27]
when I press mute I can see in the ytmdesktop program it sets the volume to 0 but the sound level does not change. it switches back to its previous sound level when I press unmute

There are tests with v1.13.0 and v1.43.0 by ytmdesktop and v1.5.0 by the plugin with the same rasultalt.

**Comment by XeroxDev** [comment]
Could you please update your issue, use the bug template and fill it out? Because I don't have all needed information.

**Comment by XeroxDev** [comment]
So. I had time to look into it. It looks like this problem comes from the YTMD Application, not from the extension. I can't do much about it. Sorry.
