### ISSUE TITLE
[BUG] Volume Down/UP on release

### ISSUE THREAD

**Issue by Kobunix** [XeroxDev/YTMD-StreamDeck#29]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - OS Version [e.g. 10]
 - Plugin Version [e.g. v1.0.4.1]
 - YTMD Version [e.g. v1.13.0]
 - Stream Deck Version [e.g. 4.9.2.13193]

**Type of plugin installation**
- [ ] Elgato Plugin Store
- [ ] GitHub repository

**Additional context**

**Comment by XeroxDev** [comment]
This is a duplicate of #28
