### ISSUE TITLE
how do i connect to YTMD

### ISSUE THREAD

**Issue by nightmarezzz** [XeroxDev/YTMD-StreamDeck#32]
i dont know how to follow this step
Activate the Companion Server / Remote control from YTMD App
Settings > Integration > "Enable Companion Server" or "Remote control" (Should be the first entry with an open icon)
i do not see these options anhywhere..
help me connect youtube music desktop with streamdeck

**Comment by XeroxDev** [comment]
1. Open the YTMDesktop app
2. Click the settings icon in the top left corner (the gear left from your profile picture)
3. A new window opens
4. In the menu on the left side, click "Integration"
5. Enable on the right, (normally) the first entry called "companion server" or "remote control"


Then you should be good to go.

**Comment by nightmarezzz** [comment]
![ytdm](https://user-images.githubusercontent.com/52876957/132439871-ca96be1f-6f82-4d5f-b994-624c1917ebc5.PNG)
I have tried everything i do not see the option of integration anywhere..

**Comment by XeroxDev** [comment]
Firstly... You need to install the right app.. You've installed the PWA (Chrome) app but this is the wrong one.

You need to install the YTMDesktop app and this was described in the plugin description and github Readme. Then everything should work.
