### ISSUE TITLE
[FEATURE]: Browser connector

### ISSUE THREAD

**Issue by XeroxDev** [XeroxDev/YTMD-StreamDeck#35]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

We should add a way to communicate with the browser / PWA from YouTube Music. So the user can either use [YTMDesktop](https://github.com/ytmdesktop/ytmdesktop) or a Browser / PWA.

### Solution

Create a extension for the following browsers:

- [ ] Google Chrome
- [ ] MS Edge
- [ ] FireFox

Also update the plugin to manage both services.

**Comment by eltharynd** [comment]
I don't see the need for it... 
Why implementing an interface from browser to the plugin, when you already have an interface from browser to YTMD?

Maybe I'm misunderstanding the request?
If you're looking to write a web app to communicate with YTMD you don't need to use the plugin as a middleware.

If you're looking for a way to interface with YTMD from anywhere else i just made public a very basic browsersource i'm using on OBS

https://github.com/eltharynd/ytm-visualizer
(sorry for kind of self promo)

**Comment by XeroxDev** [comment]
> I don't see the need for it... Why implementing an interface from browser to the plugin, when you already have an interface from browser to YTMD?
> 
> Maybe I'm misunderstanding the request? If you're looking to write a web app to communicate with YTMD you don't need to use the plugin as a middleware.
> 
> If you're looking for a way to interface with YTMD from anywhere else i just made public a very basic browsersource i'm using on OBS
> 
> https://github.com/eltharynd/ytm-visualizer (sorry for kind of self promo)

Sorry for the late answer. Strangely I didn't got notified about this comment.

This ticket is just a "Brainstorm"-Ticket (why it's on hold and low prio) and I thought this would be a nice addition for some users who are using the PWA of YTM instead of the YTMDesktop App (I got some requests from users) but currently don't have time for this.

But maybe sometime in the future I'll make some kind of extension for web browser so people also can control YTM with their MIDI device within their browser.

**Comment by XeroxDev** [comment]
I'll abondon this issue for now. Maybe I'll reopen it somewhat in the future.

/label +abondon -hold
/close
