### ISSUE TITLE
[QUESTION]: How do I connect my streamdeck to the desktop app?

### ISSUE THREAD

**Issue by NEINtje** [XeroxDev/YTMD-StreamDeck#36]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

I am trying to find out about how you can connect the ytdesktop app with my streamdeck, but I don't know how.

**Comment by XeroxDev** [comment]
# How to use the plugin

1. Install the [YouTube Music Desktop App](https://github.com/ytmdesktop/ytmdesktop).
2. Install the Plugin from [Releases](https://github.com/XeroxDev/YTMD-StreamDeck/releases) or from the official Stream
   Deck Store.
3. Add Actions to Stream Deck.
4. Activate the Companion Server / Remote control from YTMD App
    - Settings > Integration > "Enable Companion Server" or "Remote control" (Should be the first entry with an open icon)
6. Click on the open Icon or go to http://localhost:9863/ (Default)
7. Optional: Activate password protection. else go to 7.
8. Click on Play/Pause button.
9. Add all settings. (Host, Port, Password)
10. Click save
