### ISSUE TITLE
[Bug]: Album art on Track Info key does not update when Stream Deck profile is switched

### ISSUE THREAD

**Issue by cmccandless** [XeroxDev/YTMD-StreamDeck#37]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

I have two Stream Deck profiles, one as "Default" and one that triggers when the YTM Desktop app is focused, both profiles have the Track Info key on them. The Track Info key only updates album art if the song changes while the profile is active.

### Expected Behavior

Album art should appear correctly on all profiles as other track info does.

### Steps To Reproduce

1. Set up two profiles on Stream Deck, configure Stream Deck to auto-switch to one profile when YTM is active, the other as "Default", add Track Info key to both profiles, also add Next Track key
2. Open YTM Desktop, start music playback
3. Unfocus YTM, Stream Deck will switch profiles to Default. Note that the Track Info key shows correct title, album, and artist, but the album art will not be correct.
4. Press Next Track key on Stream Deck, note that Track Info key is updated as intended, including correct album art
5. Focus YTM app, Stream Deck will switch profiles to YTM profile. Note that the Track Info key shows correct title, album, and artist, but the album art will not be correct.

### OS

Windows

### OS Version

10

### Plugin Version

v1.5.2

### YTMDesktop Version

v1.13.0

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment]
Hey. Thank you for the report. I've created a hotfix for this feature.

You have a few options to update now:

1. Download it now directly from the release tab https://github.com/XeroxDev/YTMD-StreamDeck/releases
2. Wait for Elgato to approve the update and download it when it's online in the store.

**Comment by cmccandless** [comment]
I realize this was fixed a while ago, but thanks for the fast response, works great now!
