### ISSUE TITLE
[FEATURE]: Separate pause/unpause button or option in the pause/unpause button to pause or unpause only.

### ISSUE THREAD

**Issue by CatbotTsumi** [XeroxDev/YTMD-StreamDeck#44]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

As title. being able to say "make sure the music is paused/playing" is great when you're for example switching to a scene in OBS which has a video playing or gameplay providing sound. Being able to automate that without it being a toggle would be nice. 

### Solution

Solution 1: Add a Pause button that pauses the music even if its already paused. Add an Unpause button that makes sure the music is playing even if it is already playing.
Solution 2: Add in the button configuration of the Pause/Unpause button an option to select between "Toggle" "Pause" "Unpause"

**Comment by XeroxDev** [comment]
This is a good suggestion, thank you!

In the next version this will be added!
