### ISSUE TITLE
pause not working in YTMD-App v1.14.0 (Pre-Release)

### ISSUE THREAD

**Issue by Voodoohax** [XeroxDev/YTMD-StreamDeck#5]
Unable to pause on latest version, can resume play when paused through app.

**Comment by XeroxDev** [comment]
Hey. Thank you for your issue!

You've said "on latest version". Do you have both (the plugin and YTMD) on the latest version? Because I've problems to reproduce this. Can you maybe give me more information? Version number of the plugin, version number of YTMD, environment, os. Maybe so I can help you better.

**Comment by beacomedian** [comment]
I came to report the same issue. I just installed everything fresh yesterday. The system multimedia play/pause works. The plugin is connected as all the other commands work and I see the track timer in the play/pause icon. I can pause the playback with the system command, see the plugin icon update, and even restart playback with the plugin icon, but I can't pause playback.
1.14.0 of the app
1.0.3 of the Streamdeck plug.
Win10

**Comment by XeroxDev** [comment]
Thank you for the detailed information. I'll investigate this further and try to investigate and fix it ASAP.

/cib

**Comment by XeroxDev** [comment]
@beacomedian can you tell me which Elgato Stream Deck Version you're using?

**Comment by beacomedian** [comment]
ah - I'm on Streamdeck 4.9.0
I'll update to 4.9.2 and see what that reveals.

**Comment by XeroxDev** [comment]
And please try to downgrade YTMD-App to the latest stable release (v1.13.0)

**Comment by XeroxDev** [comment]
Yes. I could reproduce it on the pre-release of the YTMD-App. I will look into it if **I** have to change something or if it's a bug of the pre-release version. And I must consider: If I must change something but this will break the stable release, I need to close this issue without changing something and look into it again, when v1.14.0 is published.

**Comment by beacomedian** [comment]
repros on Streamdeck 4.9.2
fixed on YTMD App 1.13
Thanks for the tip - I didn't notice it was a pre-release

**Comment by XeroxDev** [comment]
![eade](https://user-images.githubusercontent.com/10864620/107546806-0ddd3280-6bcd-11eb-90eb-6fceedfb9472.png)
:P

**Comment by XeroxDev** [comment]
@beacomedian @Voodoohax In the release tab, there is now v1.0.4. You can download here or wait until Elgato approves this update and then it should be automatically updated via the Elgato Store.
