### ISSUE TITLE
[Bug]: Play/Pause acts as Toggle instead

### ISSUE THREAD

**Issue by playerbrodie** [XeroxDev/YTMD-StreamDeck#52]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

Having an action set to "Play" or "Pause" will instead act as "Toggle". If I have one scene with "Play" action - music will play, then switch to another scene also with "Play" action, music will pause.

### Expected Behavior

Play should only play.
Pause should only pause.

### Steps To Reproduce

Add YTMD Connector: Play-Pause
Set action "Play" or "Pause"

### OS

Windows

### OS Version

10

### Plugin Version

v1.6.0

### YTMDesktop Version

v1.13.0

### How did you download the software?

Elgato Store

**Comment by playerbrodie** [comment]
🤷‍♂️

**Comment by XeroxDev** [comment]
Oh. Sorry for the late response. I'll look into it as soon as I find time.

**Comment by tjwrona** [comment]
I am also experiencing this issue.

**Comment by tjwrona** [comment]
Note that my pull request fixes the specific issue addressed here, but the pause-play functionality still seems to be a bit buggy in general.

**Comment by XeroxDev** [comment]
Thanks to @tjwrona we found out this issue is due to an old ytmdesktop version. Please update to the latest Nightly Release.

We won't support v1.13.0 anymore and add it to the Readme as well.

I'll /close this issue. If the latest version has the same or similar issues, feel free to reopen it.
