### ISSUE TITLE
como vinculo la app con mi strteamdeck?[QUESTION]: <title>

### ISSUE THREAD

**Issue by KillerSoul82** [XeroxDev/YTMD-StreamDeck#55]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

como vinculo la app con mi strteamdeck?[QUESTION]: <title>

**Comment by XeroxDev** [comment]
Hey @KillerSoul82 

Sorry, but I can only give support in the following languages: English and German.

> como vinculo la app con mi strteamdeck?[QUESTION]: <title>
> Translated: 
> how do i link the app with my strteamdeck

Please see [6 How to use it?](https://github.com/XeroxDev/YTMD-StreamDeck#6-how-to-use-it)

**Comment by XeroxDev** [comment]
I will /close this ticket as I think this answered your question.
