### ISSUE TITLE
[Bug]: Track Info not working

### ISSUE THREAD

**Issue by franciscarriere** [XeroxDev/YTMD-StreamDeck#57]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

1. Remote configured correctly, functions work as expected (play/pause/next etc.)
2. Track info only shows the default icon, no text or album art displayed
3. Restarting either of YTMD or Stream Deck app does not fix the problem

### Expected Behavior

Track info is displayed along with album art

### Steps To Reproduce

1. Configure YTMD for remote access
2. Install YTMD-StreamDeck
3. Add Track Info to stream deck panel
4. Play a song

### OS

Windows

### OS Version

11

### Plugin Version

v1.6.0

### YTMDesktop Version

v1.13.0

### How did you download the software?

Elgato Store

**Comment by adrianh-za** [comment]
Also, Track Info seems to have a memory leak.  When adding the Track Info to the profile, memory continue to rise.  Deleting the Track Info stops memory from rising.

![image](https://user-images.githubusercontent.com/5121135/203850018-a7ebb84b-a302-47b6-bcd6-e0a5d0de4a0f.png)

**Comment by franciscarriere** [comment]
Just as an update, this seems to work now. Might have been a fix on the YTMD side?
