### ISSUE TITLE
how do i get youtube music to work on my stream deck mini

### ISSUE THREAD

**Issue by itzr0cky** [XeroxDev/YTMD-StreamDeck#60]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

i cant find out how to set up youtube music. is htere somthing i am missing that i dont see? it would be great if you could help me.

**Comment by XeroxDev** [comment]
Hey!

Could you give me some more information?

Did you everything like mentioned here: [How to use it](https://github.com/XeroxDev/YTMD-StreamDeck#6-how-to-use-it)

**Comment by XeroxDev** [comment]
I'll /close this issue due to lack of interactivity / response. Feel free to reopen it, if you're still having troubles.
