### ISSUE TITLE
link youtube

### ISSUE THREAD

**Issue by JiM2222** [XeroxDev/YTMD-StreamDeck#62]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

Hi,
I looking for to link my youtube music account with my stream deck.
I've the same problem with all plugin who needs an account.
Thank for your answer.

**Comment by XeroxDev** [comment]
This plugin is doesn't allow you to connect your YouTube account with elgato. It's just there to control [YTMDesktop](https://github.com/ytmdesktop/ytmdesktop). 

Please see the [How to use it?](https://github.com/XeroxDev/YTMD-StreamDeck#6-how-to-use-it) Section for more help

---------------------
Note: If there is no reply for a while, this issue will be closed.
