### ISSUE TITLE
[QUESTION]: <title>je comprends pas comment ça marche

### ISSUE THREAD

**Issue by Redtoutch** [XeroxDev/YTMD-StreamDeck#64]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

cette application marche avec quoi sur youtube ça ne va pas vlc non plus pas d'explication sur ytmd pourriez vous me dire sur quelle application cela fonctionne

**Comment by XeroxDev** [comment]
Sorry, I can't understand French. I only give support in the languages English and German. If you can't speak those languages, please use a translator. For the first message I make a exception:

> this application works with what on youtube it does not work vlc either no explanation on ytmd could you tell me on which application it works
- translated with Google Translate (Nice work Google, makes totally sense, lol) 

If I understand this translation correctly, you've problems using the plugin.

The Plugin is for the YTMDesktop Application. YTMDesktop is a third party application which is a wrapper to use youtube music on your computer.

The Plugin only works with that application. Please download it from the official [YTMDesktop repository](https://github.com/ytmdesktop/ytmdesktop/releases) and everything should work.
