### ISSUE TITLE
[QUESTION]: <title>the youtbe desktop app will not have a remote button to click on for me to get the port and ip info to link to my stream deck

### ISSUE THREAD

**Issue by hickerystick65** [XeroxDev/YTMD-StreamDeck#65]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

i cant find a solution for my issue

**Comment by XeroxDev** [comment]
Hello.

Did you install [YTMDesktop](https://github.com/ytmdesktop/ytmdesktop/releases)?
