### ISSUE TITLE
[FEATURE]: add to playlist button

### ISSUE THREAD

**Issue by sigsus** [XeroxDev/YTMD-StreamDeck#71]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

a button which you are able to place current playing song into X playlist, think the spotify plugin has it

**Comment by XeroxDev** [comment]
Sorry, this isn't possible right now due to missing api endpoints. Also this is a /duplicate of #50
