### ISSUE TITLE
[FEATURE]: streamdeck+ update?

### ISSUE THREAD

**Issue by marindumont** [XeroxDev/YTMD-StreamDeck#82]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

can you make an update for the streamdeck+ ?  like that we can use nodes to switch music, up or down the volume.... and i suppose also scroll list of song and push for launch the music?

**Comment by XeroxDev** [comment]
Hey. Sorry for the late response.

I tried to look things up for your mentioned device. Sadly, I don't own one my self and no one can lend me one. Don't know if I can implement this feature, without owning the hardware (can't test it or anything).

**Comment by icessassin** [comment]
Look for the YTMD Encoder Remote by Levin Ng here on Github.  He uses Xeroxs plugin as a base for a SD+ supported version.
It doesn't do much besides skip forward and back, play pause for dial press and like and dislike touchbar presses and holds.
But it is a start
