### ISSUE TITLE
[Bug]: server crash

### ISSUE THREAD

**Issue by marindumont** [XeroxDev/YTMD-StreamDeck#83]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

when i go on the setting of the app, integration and activate the server for streamdeck, the setting tab go black and if i try to go on the web server like indicate 
i have this error: 
{"message":"Route GET:/query not found","error":"Not Found","statusCode":404}

### Expected Behavior

check first comment

### Steps To Reproduce

all on first comment

### OS

Windows

### OS Version

11

### Plugin Version

 v1.7.0

### YTMDesktop Version

Version: 2.0.0-rc.1

### How did you download the software?

GitHub

**Comment by XeroxDev** [comment]
This issue doesn't seem to be related with my plugin, so I'll /close this one. If you need help with the YTMDesktop application itself, you've to ask the YTMDesktop team for help. Sorry.

Also I've seen you're using v2. This is in a really early stage and doesn't has all (important) features. Especially if you want to use it with my plugin (v2 is not yet supported).
