### ISSUE TITLE
[QUESTION]: Remote Control

### ISSUE THREAD

**Issue by Nexow91** [XeroxDev/YTMD-StreamDeck#84]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

Hello, 

hello is it possible to control the Youtube Music Player with the plugin over multiple PCs ? 

So here is the setup I have. 

2x PCs + 2 Loupdeck ct+ 

I would like to control the Youtube player on PC02 with the Loupdeck on PC01. Unfortunately I can't get a connection although I entered port, host and password. 

According to the firewall I can also listen to port 9863 from PC01, so nothing is blocked locally by the firewall.

Does anyone know if this works at all or is it due to a configuration. 

Many greetings and thanks for the cool app

**Comment by XeroxDev** [comment]
Hey and thank you for opening this issue.

The plugin should have the possibility to do this (but I haven't tested it, nor do I "officially" support it). The most important parts for this to work are:

1. PC 1/2 must can communicate with PC 2/1. Also they must be able to access the "Remote Control" page themselves (see screenshot)
2. Host has to be the same as "Ethernet" on the remote control page (see marked spot on screenshot)
3. Port must be right

This also probably means: You've to enable it in the firewall and port forwarding/routing in your router/modem (example: FritzBox)

![image](https://github.com/XeroxDev/YTMD-StreamDeck/assets/10864620/74a02301-799b-40d1-94d8-49b06360ee79)

**Comment by Nexow91** [comment]
Hi thanks for the quick feedback so I could test it now. 

I think that when Loupdeck starts it can't connect because maybe because in this time Loupdeck starts too fast. 

What I did is change the IP address of the host on PC01 from 192.x.x.110 to 192.x.x.99 and then back to 192.x.x.110. 

With this I could see 2 devices in the webpanel but unfortunately still not control them via loupdeck. 

A restart of Loupdeck did not help either. Since now only 1 Device was shown to me, so I had to repeat the IP procedure. 

The plugin still shows that no connection could be established, even after the IP test. 

According to the website are two devices available but primarily it can only control 1 Loupdeck and that is what runs locally PC02! 

I have then denoch tried to press the PC01 "Next Track" in the hope that the connection exists it Loupdeck has not realized. Unfortunately, I get a crash from the Loupdeck software and stand again at the beginning. 


https://steamuserimages-a.akamaihd.net/ugc/2115059309497494426/235D2E20AA11A00D741D4929E8D9AA12234FF20B/

**Comment by XeroxDev** [comment]
Hey! Small update:

1. I've just now noticed you're in the wrong repository lol :D you're in the StreamDeck Version, but this update also applies to you
2. V2 (StreamDeck) is very near to completion and the Loupedeck Version follows ASAP.
3. With the next update your issue should work as expected
4. Due to the fact that this is in the wrong repository, I'll gonna /close it **here** but I'll still double checking it in the Loupedeck Version, after the V2 migration is done.
