### ISSUE TITLE
[FEATURE]: Track Info Toggle

### ISSUE THREAD

**Issue by kwunhungho** [XeroxDev/YTMD-StreamDeck#89]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

A toggle function that when app is not launched (off state), then launch the app. Once app is launched (on state), show track info, 
 and when upon pressed, bring app forward instead of sending open browser link.

**Comment by XeroxDev** [comment]
I can't promise it, but I think I'll add it with the v2 YTMDesktop release.

**Comment by bbible3** [comment]
Just curious, is Track Info broken for all or for just me? It doesn't seem to be working, just showing N/A

**Comment by XeroxDev** [comment]
Hey! V2 is near to completion, but I've to inform you, that we decided against this feature. The reason for this is, that it's not that simple to add this feature through the current used plugin architecture (AFAIK I don't have any possibility to execute commands or start applications through JavaScript and rewriting the entire Plugin just for one feature isn't ideal)

We're sorry and hope you understand, but, for now, we'll add the /label +wontfix and /close this issue for now. 

Maybe, in the future, we'll reconsider and reopen this feature request.
