### ISSUE TITLE
[QUESTION]: <discord link broken, dont know how to use Library action, empty action>

### ISSUE THREAD

**Issue by JC-Thall** [XeroxDev/YTMD-StreamDeck#91]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

discord link broken, dont know how to use Library action, empty action

**Comment by XeroxDev** [comment]
Hey!

I'm not sure if I understood your question correctly, but the library action puts the current playing track into your generic library.

**Comment by XeroxDev** [comment]
I guess I can /close this issue. If your question is still up, feel free to reopen it.
