### ISSUE TITLE
is the pasuse and play meant to go to liked songs?

### ISSUE THREAD

**Issue by Kevlnnn** [XeroxDev/YTMD-StreamDeck#93]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

every time i press play or pause it always takes me to liked songs and starts playing that so i just wonder if it was a feature or a bug since it never use to do this?

**Comment by XeroxDev** [comment]
Hey!

Which version of YouTube Music Desktop are you using?

**Comment by XeroxDev** [comment]
This is the plugin version. I meant the version of the application YTMDesktop itself.

**Comment by Kevlnnn** [comment]
1.13

**Comment by XeroxDev** [comment]
v1.13 isn't supported and is full of bugs. Please use the recommended version [1.14.2 (Night Release May 2022)](https://github.com/ytmdesktop/ytmdesktop/releases/tag/1.14.2)

**Comment by XeroxDev** [comment]
Small update. This issue seems also to exists in the Nightly releases. YTMDesktop already has an open issue for this (sadly I can't fix this). See ytmdesktop/ytmdesktop#1211

**Comment by XeroxDev** [comment]
Update: #1210 fixes this issue.

**Comment by XeroxDev** [comment]
I'm gonna /close this issue as resolved, as the mentioned workaround in my comment above resolved this.

**Comment by Kevlnnn** [comment]
hello again i just wanted to point out that i tried the 1210 but i seem to not work eaither and im on 1.14 and ive copied the same as the dude on the post but still nothing 

https://github.com/XeroxDev/YTMD-StreamDeck/assets/153271025/698e0976-61c9-4197-8e4e-7f4b9bcc1191
that is a video of me showing the problem

**Comment by XeroxDev** [comment]
Like stated in the mentioned ticket above, you've to disable Play/Pause x2 in Settings > Shortcuts > Show/Hide Main Window (last entry

**Comment by Kevlnnn** [comment]
i have tried doing the same as the 1210 dude and it is still doing

**Comment by Kevlnnn** [comment]
and just real quick how do you do that

**Comment by XeroxDev** [comment]
To contact them, you can either go to their repository (via the link above) or go on their discord (discord link should be on their website, app and/or repository)
